path:
  data: /home/elasticsearch/data/data
  logs: /home/elasticsearch/data/log
network:
  host: 0.0.0.0
discovery:
  zen:
    minimum_master_nodes: 1
# Needed for docker for mac issue
bootstrap:
  ignore_system_bootstrap_checks: "true"
